apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zetanginx.fullname" . }}
  labels:
    {{- include "zetanginx.labels" . | nindent 4 }}
data:
  body: >
    <html>
      <style>
        body {
          background-color: #222;
        }
        p {
          font-family:"Courier New";
          font-size:xx-large;
          color:#f22;
          text-align:center;
        }
      </style>
      <body>
        <p>zeta test</p>
      </body>
    </html>
